seed_everything: 1415926535897932384
trainer:
  logger: true
model:
  class_path: deep_attention_visual_odometry.training_modules.CameraOptmisationTrainingModule
  init_args:
    network:
      class_path: deep_attention_visual_odometry.solvers.BFGSCameraSolver
data:
  class_path: deep_attention_visual_odometry.data_modules.CameraViewDataModule
  init_args:
    batch_size: 64
    num_workers: 8
    num_points: 128
    num_views: 6
    training_length: 1024
    validation_length: 128
    test_length: 128
