seed_everything: 1415926535
trainer:
  logger:
    # Note: Pytorch lightning uses the first logger to determine the trainers "log_dir".
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: "lightning_logs"
        name: "mlp_guess"
    - class_path: lightning.pytorch.loggers.MLFlowLogger
      init_args:
        experiment_name: "camera solvers"
        run_name: "mlp guess"
        tracking_uri: "http://localhost:8080"
        tags:
          solver: "None"
          camera_model: "pinhole"
  max_epochs: 200
#  detect_anomaly: true
  num_sanity_val_steps: 0
  callbacks:
    class_path: lightning.pytorch.callbacks.ModelSummary
    init_args:
      max_depth: 5
model:
  class_path: deep_attention_visual_odometry.training_modules.CameraOptmisationTrainingModule
  init_args:
    matmul_precision: "highest"
    network:
      class_path: deep_attention_visual_odometry.networks.InitialGuessModel
      init_args:
        initial_guess:
          class_path: deep_attention_visual_odometry.initial_guess.SimpleCameraModelMLPGuess
          init_args:
            num_views: 4
            num_points: 8
            num_hidden: 2048
            constrain: true
            init_weights: true
data:
  class_path: deep_attention_visual_odometry.data_modules.CameraViewDataModule
  init_args:
    batch_size: 256
    num_workers: 12
    num_points: 8
    num_views: 4
    training_batches: 1024
    validation_batches: 16
    test_batches: 16
