seed_everything: 1415926535897932384
trainer:
  logger: true
model:
  class_path: deep_attention_visual_odometry.training_modules.CameraOptmisationTrainingModule
  init_args:
    network:
      class_path: deep_attention_visual_odometry.networks.simple_camera_bgfs_model.SimpleCameraBGFSModel
      init_args:
        max_iterations: 2
        num_views: 3
        num_points: 8
data:
  class_path: deep_attention_visual_odometry.data_modules.CameraViewDataModule
  init_args:
    batch_size: 16
    num_workers: 0
    num_points: 8
    num_views: 3
    training_length: 1024
    validation_length: 128
    test_length: 128
